DROP TABLE IF EXISTS marbles;

CREATE TABLE marbles (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    cost INTEGER NOT NULL,
    description TEXT
);

DROP TABLE IF EXISTS snakes;

CREATE TABLE snakes (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    body_length INTEGER NOT NULL,
    venomous TEXT
);

DROP TABLE IF EXISTS books;

CREATE TABLE books (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    genre TEXT NOT NULL,
    description TEXT
);

DROP TABLE IF EXISTS hooks;

CREATE TABLE hooks (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    length INTEGER NOT NULL
);

DROP TABLE IF EXISTS homework;

CREATE TABLE homework (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    completed BOOLEAN NOT NULL
);
